sudo: false
language: php

php:
    - 5.4
    - 5.5
    - 5.6

before_script:
  - mysql -e 'create database phpauthtest;'
  - mysql -u root phpauthtest < database.sql

script:
    - phpunit

notifications:
    email: false
